library(ggplot2)
library(gridExtra)
library(grid)
library(gtable)

setwd("~/branch/badDiamond/res/mainTextFigure/rootNNI")

# Create user-defined function, which extracts legends from ggplots
extract_legend <- function(my_ggp) {
  step1 <- ggplot_gtable(ggplot_build(my_ggp))
  step2 <- which(sapply(step1$grobs, function(x) x$name) == "guide-box")
  step3 <- step1$grobs[[step2]]
  return(step3)
}

####
#Balanced Root
####
d1 <- read.table("d1.r1.txt", sep = "\t",header=TRUE)
p111 <- ggplot(d1, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 1",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5)) + ggtitle("Root 1")
p112 <- ggplot(d1, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 1",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5)) + ggtitle("Root 1")
p113 <- ggplot(d1, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 1",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5)) + ggtitle("Root 1")

d2 <- read.table("d2.r1.txt", sep = "\t",header=TRUE)
p211 <- ggplot(d2, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 2",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p212 <- ggplot(d2, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 2",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p213 <- ggplot(d2, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 2",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d3 <- read.table("d3.r1.txt", sep = "\t",header=TRUE)
p311 <- ggplot(d3, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 3",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p312 <- ggplot(d3, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 3",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p313 <- ggplot(d3, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 3",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d4 <- read.table("d4.r1.txt", sep = "\t",header=TRUE)
p411 <- ggplot(d4, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 4",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p412 <- ggplot(d4, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 4",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p413 <- ggplot(d4, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 4",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d5 <- read.table("d5.r1.txt", sep = "\t",header=TRUE)
p511 <- ggplot(d5, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 5",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p512 <- ggplot(d5, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 5",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p513 <- ggplot(d5, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 5",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d6 <- read.table("d6.r1.txt", sep = "\t",header=TRUE)
p611 <- ggplot(d6, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 6",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p612 <- ggplot(d6, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 6",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p613 <- ggplot(d6, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 6",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d7 <- read.table("d7.r1.txt", sep = "\t",header=TRUE)
p711 <- ggplot(d7, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 7",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p712 <- ggplot(d7, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 7",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p713 <- ggplot(d7, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 7",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d8 <- read.table("d8.r1.txt", sep = "\t",header=TRUE)
p811 <- ggplot(d8, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 8",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p812 <- ggplot(d8, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 8",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p813 <- ggplot(d8, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 8",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d9 <- read.table("d9.r1.txt", sep = "\t",header=TRUE)
p911 <- ggplot(d9, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 9",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p912 <- ggplot(d9, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 9",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p913 <- ggplot(d9, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Diamond 9",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

####
#Ladderized Root
####

d1 <- read.table("d1.r2.txt", sep = "\t",header=TRUE)
p121 <- ggplot(d1, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5)) + ggtitle("Root 2")
p122 <- ggplot(d1, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5)) + ggtitle("Root 2")
p123 <- ggplot(d1, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5)) + ggtitle("Root 2")

d2 <- read.table("d2.r2.txt", sep = "\t",header=TRUE)
p221 <- ggplot(d2, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p222 <- ggplot(d2, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p223 <- ggplot(d2, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d3 <- read.table("d3.r2.txt", sep = "\t",header=TRUE)
p321 <- ggplot(d3, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p322 <- ggplot(d3, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p323 <- ggplot(d3, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d4 <- read.table("d4.r2.txt", sep = "\t",header=TRUE)
p421 <- ggplot(d4, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p422 <- ggplot(d4, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p423 <- ggplot(d4, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d5 <- read.table("d5.r2.txt", sep = "\t",header=TRUE)
p521 <- ggplot(d5, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p522 <- ggplot(d5, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p523 <- ggplot(d5, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d6 <- read.table("d6.r2.txt", sep = "\t",header=TRUE)
p621 <- ggplot(d6, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p622 <- ggplot(d6, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p623 <- ggplot(d6, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d7 <- read.table("d7.r2.txt", sep = "\t",header=TRUE)
p721 <- ggplot(d7, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p722 <- ggplot(d7, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p723 <- ggplot(d7, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d8 <- read.table("d8.r2.txt", sep = "\t",header=TRUE)
p821 <- ggplot(d8, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p822 <- ggplot(d8, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p823 <- ggplot(d8, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d9 <- read.table("d9.r2.txt", sep = "\t",header=TRUE)
p921 <- ggplot(d9, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p922 <- ggplot(d9, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p923 <- ggplot(d9, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))


####
#Outgroup Root
####

d1 <- read.table("d1.r3.txt", sep = "\t",header=TRUE)
p131 <- ggplot(d1, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5)) + ggtitle("Root 3")
p132 <- ggplot(d1, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5)) + ggtitle("Root 3")
p133 <- ggplot(d1, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5)) + ggtitle("Root 3")

d2 <- read.table("d2.r3.txt", sep = "\t",header=TRUE)
p231 <- ggplot(d2, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p232 <- ggplot(d2, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p233 <- ggplot(d2, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d3 <- read.table("d3.r3.txt", sep = "\t",header=TRUE)
p331 <- ggplot(d3, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p332 <- ggplot(d3, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p333 <- ggplot(d3, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d4 <- read.table("d4.r3.txt", sep = "\t",header=TRUE)
p431 <- ggplot(d4, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p432 <- ggplot(d4, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p433 <- ggplot(d4, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d5 <- read.table("d5.r3.txt", sep = "\t",header=TRUE)
p531 <- ggplot(d5, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p532 <- ggplot(d5, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p533 <- ggplot(d5, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d6 <- read.table("d6.r3.txt", sep = "\t",header=TRUE)
p631 <- ggplot(d6, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p632 <- ggplot(d6, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p633 <- ggplot(d6, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d7 <- read.table("d7.r3.txt", sep = "\t",header=TRUE)
p731 <- ggplot(d7, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p732 <- ggplot(d7, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p733 <- ggplot(d7, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d8 <- read.table("d8.r3.txt", sep = "\t",header=TRUE)
p831 <- ggplot(d8, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p832 <- ggplot(d8, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p833 <- ggplot(d8, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep="")),expression(paste("",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))

d9 <- read.table("d9.r3.txt", sep = "\t",header=TRUE)
p931 <- ggplot(d9, aes(x=xPos,y=FoundOneEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p932 <- ggplot(d9, aes(x=xPos,y=CorrectNetwork/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
p933 <- ggplot(d9, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method),alpha=1.0)) + geom_point(size=2) +scale_color_manual(values=c("#d8b365","#034e7b")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("","","","",""), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "none", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))


plegend <- ggplot(d9, aes(x=xPos,y=HasHybridEdge/100,color=factor(Method))) + geom_point(size=2) +scale_color_manual(name="Estimator",values=c("#034e7b","#d8b365"),labels=c("SNaQ","InferNetwork_MPL")) + scale_x_continuous(name=expression(paste("nLoci",sep="")), breaks=c(1,2,3,4),labels=c(expression(paste("100",sep="")),expression(paste("500",sep="")),expression(paste("1000",sep="")),expression(paste("5000",sep=""))),limits=c(0.5,4.5)) + scale_y_continuous(name=expression(paste("Hybrid Edge Recovered",sep="")), breaks=c(0,0.25,0.5,0.75,1.0),labels=c("0","0.25","0.5","0.75","1.0"), limits=c(-0.1,1.1)) + theme(panel.background = element_rect(fill='white', colour='black'),panel.grid.minor.y = element_blank(),panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), axis.title = element_text(size = 8), legend.position = "bottom", axis.text.x = element_text(size=6), axis.text.y = element_text(size=6), panel.grid.major.x = element_blank(), plot.margin=unit(c(0.05,0.05,0.05,0.05),"in"),plot.title = element_text(size=10, hjust = 0.5))
# Apply user-defined function to extract legend
shared_legend <- extract_legend(plegend)

g <- grid.arrange(arrangeGrob(p113, p123, p133, p213, p223, p233, p313, p323, p333, p413, p423, p433, p513, p523, p533, p613, p623, p633, p713, p723, p733, p813, p823, p833, p913, p923, p933, ncol = 3),shared_legend, nrow = 2, heights = c(11, 1))

ggsave("withError.pdf",g,device="pdf",units="in",width=6.5,height=8.0)
